language: ruby
cache: bundler
rbenv:
- 2.4.1
services:
- postgresql
before_script:
- bundle exec rake db:{drop,create,migrate,seed}
env:
  matrix:
  - secure: VVQWaSZsC+61RcbOb0eO3n+2BGV+XNZdDWn8KGs72HTkBVsyJ8W3abkdk8ZIQVuRYM+UrlBg94DQR0dzkRhSfKtJcua4h17mU0tPsf/ah1K4cDcn1d3rtDuVAL7Mif38uh4hpDBVYxNkSpm4EdBc+ng8ujYDbOVobDXYsWVFkI5+bnq3uFbuo2kheecYwZk0ZgrdRBtzbe9o77cGm6yo4SGGs8vRjBkOz6lReO6W+DMJCnoQhNcul4ZeT1BWHCjAEXZdyDe06aBSIfLvVbKj9KDv/jdKFonH0Z4tbUnyEikmd/lHCHQc9Z0Xqldu65vo3XqO2jFsIWoAK/TUSBJI7T7O+dMiVpTOdi1nfcXXzRJvo9D6R45ApLwpRWtVAWwQSl0VuonB6my6PQnSd/TkMD1eW8BA7N8EsNoak5V6NkAXswjJ2jtpsLKPaB62vyBbfNgFknpOfp/A3E/68Zh/DjJCHB6yFUP7q8B1cQ+m4x55afWRFNFiqHg4jTLB6t1qQ2ktZDRDLHo076E8AAOg20MUszmduWDldaBEILrUgouwM/NDBqOjkoQC63T5g9HgOQZV2IBm7tAL7EqcV2C9EYED4YfYFz4JBrG80aZ+Twlg5MJuQ+bZaVFAESsP5hYJS6dHbQB4gOi8n9CYTYaiqC19AlTqj8c2guLp7uhJMVk=
  # - secure: vQhgfvUhZ9QUBvLwb29HhXMyJOoBWc4ngi5GSN5vVXzX59zfig4xKjnFieT/I7XCYHGRlgZiNd0wRJ2lvZ3d++KnrcnpM2AIfpXrahoTamMFDB7EKxoZoAPgKCPg77+it0U/KqD2tabuuMK9X6++kXMSHY8q+cQx3k/UWfP2SB+ZI/cF0FNQ9AK9j3H2O6WyKqd7hw1q8UjcbnCtofXNISWEBvxBobqnuG78Yik8CDnGaiC7hG9/ulc2xmcS6D2yHMt1eJCQQnnk8vtk/52gncv334yAbKGFZJfk9c2z8wG2vdTf0fpnG7GupcVAHarysBBt9wLZxYymmRU3bWprsbjhuqdaCQVR4aby76GZMDwKGou+CtNNSFUlmYvn+uI599zOkpza3lfRUCOL8rqn1OLcQZ67BHncDsvA4uxSV6FgwmGw/dqIjByXpcF3q6kyI8g8dh+66Xo/pk0FDuokNnRNkEYKncHdD9wsIU5juYK5ZKa623hrLdqbSbfNpyw9qFjQSS0QYTipYfgZ27xUG1ecxqb1ts2DalJzHqY37g0pVl+y3Hh4RAtu5dNGh9+yYecDL0R1U6wmvzfbhS+IU5lkkmuGPwVy274IQbjdIlY3MSPRhygbZqYkptWMVtzE9SxGj9D8pSZCHmcyYRQlCj2xbNlHYLTR/aB4diCzqbo=
